// data-groups.js — fake scan-group catalogue

window.GROUPS = [
  {
    id:'sc', name:'Scan Central', tag:'@scancentral',
    avatar:'#ddda2a', cover:'linear-gradient(135deg,#2a1f0f,#161616)',
    bio:'Scan brasileira focada em shounen e seinen. Tradução cuidadosa, revisão dupla e cleaning impecável desde 2018.',
    founded:'Mar 2018', city:'São Paulo, BR',
    members:1240, followers:18432, following:false,
    translated:42, chapters:3214,
    genres:['Shounen','Seinen','Aventura','Dark Fantasy','Sobrenatural'],
    socials:{ discord:'discord.gg/scancentral', twitter:'@scancentral_br', site:'scancentral.com.br' },
    works:['op','bk','jk','cs','vm'],
    team:[
      { initials:'AK', role:'Líder',     name:'AkariReads' },
      { initials:'KJ', role:'Tradutor',  name:'Kenji_99' },
      { initials:'YL', role:'Revisor',   name:'YukiLove' },
      { initials:'RM', role:'Cleaner',   name:'Ruan' },
      { initials:'TS', role:'Typesetter',name:'Takeshi' },
      { initials:'MN', role:'Tradutor',  name:'Mina' },
    ],
  },
  {
    id:'ot', name:'Otaku Translators', tag:'@otaku.tl',
    avatar:'#FF784F', cover:'linear-gradient(135deg,#3a1010,#161616)',
    bio:'Coletivo dedicado a obras de nicho — josei, slice of life e mangás esquecidos pelo tempo.',
    founded:'Jul 2020', city:'Recife, BR',
    members:820, followers:9210, following:true,
    translated:28, chapters:1840,
    genres:['Josei','Slice of Life','Romance','Drama'],
    socials:{ discord:'discord.gg/otakutl', twitter:'@otakutl' },
    works:['fr','dg','ks'],
    team:[
      { initials:'MN', role:'Líder',     name:'Mina' },
      { initials:'JL', role:'Tradutor',  name:'Julia' },
      { initials:'PC', role:'Revisor',   name:'Pedro' },
      { initials:'AN', role:'Cleaner',   name:'Ana' },
    ],
  },
  {
    id:'ps', name:'Panda Scans', tag:'@pandascans',
    avatar:'#1f3a2a', cover:'linear-gradient(135deg,#1f2a3a,#161616)',
    bio:'A maior scan de manhwa do Brasil. Foco em ação, isekai e sistema. Lançamentos diários.',
    founded:'Set 2021', city:'Rio de Janeiro, BR',
    members:2110, followers:34221, following:false,
    translated:67, chapters:5210,
    genres:['Manhwa','Ação','Isekai','Sistema','Reencarnação'],
    socials:{ discord:'discord.gg/pandascans', twitter:'@panda_br', site:'pandascans.com.br' },
    works:['sl','mt'],
    team:[
      { initials:'PN', role:'Líder',     name:'Panda' },
      { initials:'KM', role:'Tradutor',  name:'Kim' },
      { initials:'LC', role:'Revisor',   name:'Lucas' },
    ],
  },
  {
    id:'ns', name:'Noturnos Scan', tag:'@noturnos',
    avatar:'#2a1f3a', cover:'linear-gradient(135deg,#2a1f3a,#161616)',
    bio:'Noite adentro, traduzindo o que ninguém mais traduz. Horror, mistério e psicológico.',
    founded:'Out 2019', city:'Belo Horizonte, BR',
    members:410, followers:5120, following:false,
    translated:19, chapters:980,
    genres:['Horror','Psicológico','Mistério','Seinen'],
    socials:{ discord:'discord.gg/noturnos' },
    works:['bk'],
    team:[
      { initials:'NT', role:'Líder',     name:'Noturno' },
      { initials:'SL', role:'Tradutor',  name:'Silvia' },
    ],
  },
];
