// data-tags.js — tags/gêneros (espelha a tela atual; IDs não-sequenciais, como no app)
window.ADMIN_TAGS = [
  { id: 1,  name: 'Ação' },
  { id: 2,  name: 'Aventura' },
  { id: 3,  name: 'Comédia' },
  { id: 4,  name: 'Drama' },
  { id: 5,  name: 'Fantasia' },
  { id: 6,  name: 'Ficção Científica' },
  { id: 7,  name: 'Horror' },
  { id: 8,  name: 'Mistério' },
  { id: 9,  name: 'Romance' },
  { id: 10, name: 'Seinen' },
  { id: 11, name: 'Shoujo' },
  { id: 12, name: 'Shounen' },
  { id: 13, name: 'Slice of Life' },
  { id: 14, name: 'Sobrenatural' },
  { id: 15, name: 'Histórico' },
  { id: 16, name: 'Suspense' },
  { id: 17, name: 'Artes Marciais' },
  { id: 18, name: 'Esportes' },
  { id: 19, name: 'Culinária' },
  { id: 20, name: 'Psicológico' },
  { id: 21, name: 'RPG' },
  { id: 22, name: 'Escolar' },
  { id: 23, name: 'Mecha' },
  { id: 24, name: 'Musical' },
];
