// data-news.js — notícias (espelha a tela atual)
window.NEWS_CATEGORIES = ['Lançamentos', 'Adaptações', 'Principais', 'Entrevistas', 'Indústria', 'Eventos', 'Curiosidades', 'Mercado', 'Internacional'];

const L = (pt) => ({ 'pt-BR': pt, 'en-US': '', 'es-ES': '' });

window.ADMIN_NEWS = [
  { id: 'news-1',  title: "Novo mangá de fantasia 'Reino de Aço' bate recordes de vendas", category: 'Lançamentos', views: 3200, featured: true,  exclusive: false, published: '10/06/2026', source: 'Panini Comics', author: 'Redação MangaReader', readTime: 4, tags: 'Reino de Aço, Vendas, Mangá, Panini', subtitle: L('A obra ultrapassou 500 mil cópias vendidas em apenas 3 meses'), summary: L('O mangá de estreia de Takeshi Yamamoto se consolida como o grande sucesso do ano.'), cover: 'https://picsum.photos/800/450?random=301' },
  { id: 'news-2',  title: 'Solo Leveling confirma 3ª temporada do anime para 2026', category: 'Adaptações', views: 8500, featured: true, exclusive: false, published: '09/06/2026', source: 'A-1 Pictures', author: 'Redação MangaReader', readTime: 3, tags: 'Solo Leveling, Anime, Temporada', subtitle: L('Estúdio A-1 Pictures retorna para a nova temporada'), summary: L('A adaptação mais aguardada do ano ganha continuação confirmada.'), cover: 'https://picsum.photos/800/450?random=302' },
  { id: 'news-3',  title: 'Guia: os melhores mangás de 2025 segundo os leitores', category: 'Principais', views: 5400, featured: false, exclusive: false, published: '08/06/2026', source: 'MangaReader', author: 'Redação MangaReader', readTime: 8, tags: 'Guia, Melhores, 2025', subtitle: L('Uma curadoria votada pela comunidade'), summary: L('Reunimos as obras mais bem avaliadas do ano pelos nossos leitores.'), cover: 'https://picsum.photos/800/450?random=303' },
  { id: 'news-4',  title: 'Editora NewPOP anuncia 5 novos manhwas para o catálogo brasileiro', category: 'Lançamentos', views: 2100, featured: false, exclusive: false, published: '07/06/2026', source: 'NewPOP', author: 'Redação MangaReader', readTime: 3, tags: 'NewPOP, Manhwa, Catálogo', subtitle: L('Lançamentos previstos para o segundo semestre'), summary: L('A editora aposta em títulos de romance e ação para o público brasileiro.'), cover: 'https://picsum.photos/800/450?random=304' },
  { id: 'news-5',  title: 'Entrevista exclusiva: Hiroshi Tanaka fala sobre Crônicas de Polaris', category: 'Entrevistas', views: 4300, featured: false, exclusive: true, published: '06/06/2026', source: 'MangaReader', author: 'Ana Beatriz', readTime: 10, tags: 'Entrevista, Hiroshi Tanaka, Polaris', subtitle: L('O autor revela bastidores da criação'), summary: L('Conversamos com Hiroshi Tanaka sobre o processo criativo de sua obra mais aclamada.'), cover: 'https://picsum.photos/800/450?random=305' },
  { id: 'news-6',  title: 'Shueisha registra crescimento de 30% em receita digital', category: 'Indústria', views: 1800, featured: false, exclusive: false, published: '05/06/2026', source: 'Shueisha', author: 'Redação MangaReader', readTime: 5, tags: 'Shueisha, Digital, Receita', subtitle: L('O mercado digital segue em expansão'), summary: L('A editora japonesa aponta o digital como motor de crescimento.'), cover: 'https://picsum.photos/800/450?random=306' },
  { id: 'news-7',  title: 'AnimeCon SP 2026: tudo que sabemos até agora', category: 'Eventos', views: 6200, featured: true, exclusive: false, published: '04/06/2026', source: 'MangaReader', author: 'Redação MangaReader', readTime: 6, tags: 'AnimeCon, Evento, São Paulo', subtitle: L('Datas, convidados e ingressos'), summary: L('Reunimos todas as informações confirmadas sobre o maior evento do ano.'), cover: 'https://picsum.photos/800/450?random=307' },
  { id: 'news-8',  title: '10 curiosidades sobre a criação de mangás que você não sabia', category: 'Curiosidades', views: 0, featured: false, exclusive: false, published: '03/06/2026', source: 'MangaReader', author: 'Redação MangaReader', readTime: 7, tags: 'Curiosidades, Bastidores', subtitle: L('Fatos surpreendentes da indústria'), summary: L('Do storyboard à impressão: detalhes que poucos leitores conhecem.'), cover: 'https://picsum.photos/800/450?random=308' },
  { id: 'news-9',  title: 'Mercado brasileiro de mangás cresce 45% e se torna o 3º maior do mundo', category: 'Mercado', views: 1000000, featured: true, exclusive: false, published: '02/06/2026', source: 'MangaReader', author: 'Redação MangaReader', readTime: 5, tags: 'Mercado, Brasil, Crescimento', subtitle: L('Brasil agora atrás apenas de Japão e EUA'), summary: L('O país consolida sua posição como potência no consumo de mangás.'), cover: 'https://picsum.photos/800/450?random=309' },
  { id: 'news-10', title: 'Japão aprova nova lei de proteção a direitos autorais de mangás digitais', category: 'Internacional', views: 3400, featured: false, exclusive: false, published: '01/06/2026', source: 'NHK', author: 'Redação MangaReader', readTime: 4, tags: 'Japão, Direitos Autorais, Lei', subtitle: L('Medida combate a pirataria digital'), summary: L('A nova legislação endurece as penas contra a distribuição ilegal.'), cover: 'https://picsum.photos/800/450?random=310' },
];
