// data-events.js — eventos (espelha a tela atual)
window.EVENT_TYPES = ['Lançamento', 'Convenção', 'Workshop', 'Meetup', 'Live'];
window.EVENT_STATUSES = ['Em breve', 'Inscrições abertas', 'Acontecendo agora', 'Encerrado'];
window.EVENT_TIMELINES = ['Próximos', 'Em andamento', 'Passados'];
window.EVENT_STATUS_TONE = { 'Em breve': 'soon', 'Inscrições abertas': 'open', 'Acontecendo agora': 'live', 'Encerrado': 'ended' };

const LE = (pt) => ({ 'pt-BR': pt, 'en-US': '', 'es-ES': '' });

window.ADMIN_EVENTS = [
  { id: '1cf05fea', title: 'Noite de Autógrafos — Hiroshi Tanaka', type: 'Lançamento', status: 'Em breve', timeline: 'Próximos', city: 'São Paulo', local: 'Livraria Cultura — Conjunto Nacional', start: '25/07/2026', online: false, featured: false, organizer: 'Panini Comics', price: 'Gratuito com compra do volume', image: 'https://picsum.photos/1200/600?random=504', subtitle: LE('Sessão exclusiva com o autor de Crônicas de Polaris'), description: LE('Hiroshi Tanaka estará presente para uma sessão de autógrafos e bate-papo sobre a criação de Crônicas de Polaris.') },
  { id: '1c2ffca7', title: 'AnimeCon SP 2026', type: 'Convenção', status: 'Inscrições abertas', timeline: 'Próximos', city: 'São Paulo', local: 'São Paulo Expo', start: '10/07/2026', online: false, featured: true, organizer: 'AnimeCon', price: 'A partir de R$ 80,00', image: 'https://picsum.photos/1200/600?random=505', subtitle: LE('O maior evento de cultura pop do país'), description: LE('Três dias de painéis, estandes, cosplay e convidados internacionais.') },
  { id: '326b9eca', title: 'Workshop Online: Colorização Digital de Mangá', type: 'Workshop', status: 'Inscrições abertas', timeline: 'Próximos', city: 'Online', local: 'Online', start: '01/07/2026', online: true, featured: false, organizer: 'MangaReader', price: 'R$ 49,90', image: 'https://picsum.photos/1200/600?random=506', subtitle: LE('Aprenda técnicas profissionais de cor'), description: LE('Workshop ao vivo com um colorista profissional, com certificado de participação.') },
  { id: '1de825fc', title: 'Meetup Leitores MangaReader — Rio de Janeiro', type: 'Meetup', status: 'Inscrições abertas', timeline: 'Próximos', city: 'Rio de Janeiro', local: 'Livraria da Travessa — Botafogo', start: '24/06/2026', online: false, featured: false, organizer: 'Comunidade MangaReader', price: 'Gratuito', image: 'https://picsum.photos/1200/600?random=507', subtitle: LE('Encontro presencial da comunidade'), description: LE('Venha conhecer outros leitores, trocar recomendações e participar de sorteios.') },
  { id: 'b06e1976', title: 'Live: Debate — Melhores Manhwas de Ação', type: 'Live', status: 'Em breve', timeline: 'Próximos', city: 'Online', local: 'YouTube MangaReader', start: '17/06/2026', online: true, featured: false, organizer: 'MangaReader', price: 'Gratuito', image: 'https://picsum.photos/1200/600?random=508', subtitle: LE('Transmissão ao vivo com convidados'), description: LE('Um debate descontraído sobre os melhores manhwas de ação da atualidade.') },
  { id: '75e4f6d4', title: 'Live: Análise dos Lançamentos de Março', type: 'Live', status: 'Acontecendo agora', timeline: 'Em andamento', city: 'Online', local: 'YouTube MangaReader', start: '10/06/2026', online: true, featured: false, organizer: 'MangaReader', price: 'Gratuito', image: 'https://picsum.photos/1200/600?random=509', subtitle: LE('Ao vivo agora'), description: LE('Comentamos os principais lançamentos do mês com a participação do público no chat.') },
  { id: '634257d5', title: 'Lançamento: Noites Vermelhas — Vol. 1', type: 'Lançamento', status: 'Acontecendo agora', timeline: 'Em andamento', city: 'São Paulo', local: 'Comix Book Shop', start: '10/06/2026', online: false, featured: true, organizer: 'Panini Comics', price: 'Gratuito', image: 'https://picsum.photos/1200/600?random=510', subtitle: LE('Estreia do volume físico'), description: LE('Lançamento oficial com sessão de autógrafos e brindes para os primeiros visitantes.') },
  { id: '10ea3e61', title: 'Workshop: Introdução ao Desenho de Mangá', type: 'Workshop', status: 'Encerrado', timeline: 'Passados', city: 'São Paulo', local: 'Centro Cultural', start: '26/05/2026', online: false, featured: false, organizer: 'MangaReader', price: 'R$ 39,90', image: 'https://picsum.photos/1200/600?random=511', subtitle: LE('Para iniciantes'), description: LE('Uma introdução prática às técnicas básicas de desenho de mangá.') },
  { id: '8a145fec', title: 'Meetup Tradutores de Mangá — SP', type: 'Meetup', status: 'Encerrado', timeline: 'Passados', city: 'São Paulo', local: 'Coworking Vila Madalena', start: '11/05/2026', online: false, featured: false, organizer: 'Comunidade MangaReader', price: 'Gratuito', image: 'https://picsum.photos/1200/600?random=512', subtitle: LE('Encontro de scanlators'), description: LE('Um espaço para tradutores e editores trocarem experiências e boas práticas.') },
  { id: '4ac37337', title: 'Manga Fest BH 2025', type: 'Convenção', status: 'Encerrado', timeline: 'Passados', city: 'Belo Horizonte', local: 'Expominas', start: '11/04/2026', online: false, featured: false, organizer: 'Manga Fest', price: 'A partir de R$ 60,00', image: 'https://picsum.photos/1200/600?random=513', subtitle: LE('Edição 2025 do festival'), description: LE('O tradicional festival mineiro de mangás e cultura japonesa.') },
];
