// data-titles.js — catálogo de obras (espelha a tela atual de Títulos)
window.ADMIN_TITLES = [
  { id: 1,  name: 'Reino de Aço',         type: 'Mangá',  status: 'Em andamento', chapters: 8, created: '10/06/2026', author: 'Takeshi Yamamoto', artist: 'Takeshi Yamamoto', publisher: 'Panini', genres: 'Ação, Aventura, Fantasia', adult: false, cover: 'https://picsum.photos/300/450?random=101',
    synopsis: { 'pt-BR': 'Em um mundo onde armaduras vivas dominam os campos de batalha, um ferreiro órfão descobre que seu sangue pode despertar a lendária Armadura Negra.', 'en-US': '', 'es-ES': '' } },
  { id: 2,  name: 'Lâmina do Amanhã',     type: 'Manhwa', status: 'Em andamento', chapters: 6, created: '10/06/2026', author: 'Ji-ho Park', artist: 'Ji-ho Park', publisher: 'NewPOP', genres: 'Ação, Drama', adult: false, cover: 'https://picsum.photos/300/450?random=102', synopsis: { 'pt-BR': 'Uma assassina renascida cruza linhas do tempo para impedir a guerra que destruiu seu mundo.', 'en-US': '', 'es-ES': '' } },
  { id: 3,  name: 'Flores de Neon',       type: 'Mangá',  status: 'Concluído',    chapters: 5, created: '10/06/2026', author: 'Aiko Tanaka', artist: 'Aiko Tanaka', publisher: 'JBC', genres: 'Romance, Slice of Life', adult: false, cover: 'https://picsum.photos/300/450?random=103', synopsis: { 'pt-BR': 'Duas garotas se encontram todas as noites sob os letreiros de neon de uma Tóquio que nunca dorme.', 'en-US': '', 'es-ES': '' } },
  { id: 4,  name: 'Crônicas de Polaris',  type: 'Mangá',  status: 'Em andamento', chapters: 7, created: '10/06/2026', author: 'Hiroshi Tanaka', artist: 'Hiroshi Tanaka', publisher: 'Panini', genres: 'Ficção Científica, Aventura', adult: false, cover: 'https://picsum.photos/300/450?random=104', synopsis: { 'pt-BR': 'A última nave-colônia da humanidade segue rumo à estrela Polaris carregando um segredo capaz de mudar tudo.', 'en-US': '', 'es-ES': '' } },
  { id: 5,  name: 'Vento Cortante',       type: 'Manhwa', status: 'Em andamento', chapters: 5, created: '10/06/2026', author: 'Min-jun Kim', artist: 'Min-jun Kim', publisher: 'NewPOP', genres: 'Artes Marciais, Ação', adult: false, cover: 'https://picsum.photos/300/450?random=105', synopsis: { 'pt-BR': 'Um espadachim cego desce das montanhas para vingar seu mestre.', 'en-US': '', 'es-ES': '' } },
  { id: 6,  name: 'Guardião Celestial',   type: 'Manhua', status: 'Hiato',        chapters: 6, created: '10/06/2026', author: 'Wei Chen', artist: 'Wei Chen', publisher: 'Independente', genres: 'Fantasia, Cultivo', adult: false, cover: 'https://picsum.photos/300/450?random=106', synopsis: { 'pt-BR': 'Um jovem desperta como herdeiro de um deus esquecido e precisa reerguer um templo em ruínas.', 'en-US': '', 'es-ES': '' } },
  { id: 7,  name: 'Coração de Porcelana', type: 'Mangá',  status: 'Concluído',    chapters: 4, created: '10/06/2026', author: 'Sora Mizuki', artist: 'Sora Mizuki', publisher: 'JBC', genres: 'Romance, Drama', adult: false, cover: 'https://picsum.photos/300/450?random=107', synopsis: { 'pt-BR': 'Uma restauradora de cerâmica aprende que algumas pessoas, como o kintsugi, ficam mais belas após se quebrarem.', 'en-US': '', 'es-ES': '' } },
  { id: 8,  name: 'Protocolo Zero',       type: 'Manhwa', status: 'Em andamento', chapters: 5, created: '10/06/2026', author: 'Seo-yeon Lee', artist: 'Seo-yeon Lee', publisher: 'NewPOP', genres: 'Ficção Científica, Thriller', adult: true, cover: 'https://picsum.photos/300/450?random=108', synopsis: { 'pt-BR': 'Quando a IA que governa a cidade trava, o único humano com acesso ao Protocolo Zero precisa decidir quem vive.', 'en-US': '', 'es-ES': '' } },
  { id: 9,  name: 'Noites Vermelhas',     type: 'Mangá',  status: 'Hiato',        chapters: 3, created: '10/06/2026', author: 'Ryo Saito', artist: 'Ryo Saito', publisher: 'Panini', genres: 'Horror, Mistério', adult: true, cover: 'https://picsum.photos/300/450?random=109', synopsis: { 'pt-BR': 'Em uma vila isolada, o sol não nasce há sete dias — e os mortos começaram a sussurrar.', 'en-US': '', 'es-ES': '' } },
  { id: 10, name: 'Espelho do Vazio',     type: 'Manhua', status: 'Cancelado',    chapters: 6, created: '10/06/2026', author: 'Lan Yu', artist: 'Lan Yu', publisher: 'Independente', genres: 'Fantasia, Psicológico', adult: false, cover: 'https://picsum.photos/300/450?random=110', synopsis: { 'pt-BR': 'Cada reflexo guarda uma versão de você que tomou a decisão oposta. E uma delas quer sair.', 'en-US': '', 'es-ES': '' } },
];

window.TITLE_TYPES = ['Mangá', 'Manhwa', 'Manhua'];
window.TITLE_STATUSES = ['Em andamento', 'Concluído', 'Hiato', 'Cancelado'];
window.TITLE_STATUS_TONE = { 'Em andamento': 'live', 'Concluído': 'open', 'Hiato': 'soon', 'Cancelado': 'ended' };
