-- =============================================================================
-- V1__initial_schema.sql
-- Manga Reader — Schema Inicial PostgreSQL
-- =============================================================================
-- Cria todas as 14 tabelas em ordem segura de dependência (FKs).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. users  (referenciada por muitas tabelas)
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id              UUID            NOT NULL PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL,
    email           VARCHAR(255)    NOT NULL UNIQUE,
    password_hash   VARCHAR(255)    NOT NULL,
    bio             VARCHAR(500),
    photo_url       VARCHAR(255),
    role            VARCHAR(20)     NOT NULL,
    created_at      TIMESTAMP       NOT NULL,
    updated_at      TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 2. tags  (PK BIGINT com IDENTITY — única tabela sem UUID)
-- ---------------------------------------------------------------------------
CREATE TABLE tags (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label   VARCHAR(60) NOT NULL UNIQUE
);

-- ---------------------------------------------------------------------------
-- 3. stores
-- ---------------------------------------------------------------------------
CREATE TABLE stores (
    id              UUID            NOT NULL PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL,
    logo            VARCHAR(255),
    icon            VARCHAR(255),
    description     VARCHAR(2000),
    website         VARCHAR(255)    NOT NULL,
    availability    VARCHAR(20),
    rating          DOUBLE PRECISION,
    features        JSONB           DEFAULT '[]'::jsonb
);

-- ---------------------------------------------------------------------------
-- 4. groups
-- ---------------------------------------------------------------------------
CREATE TABLE groups (
    id                  UUID            NOT NULL PRIMARY KEY,
    name                VARCHAR(100)    NOT NULL,
    username            VARCHAR(50)     NOT NULL UNIQUE,
    logo                VARCHAR(255),
    banner              VARCHAR(255),
    description         VARCHAR(2000),
    website             VARCHAR(255),
    total_titles        INTEGER         DEFAULT 0,
    founded_year        INTEGER,
    status              VARCHAR(20)     NOT NULL,
    genres              JSONB           DEFAULT '[]'::jsonb,
    focus_tags          JSONB           DEFAULT '[]'::jsonb,
    rating              DOUBLE PRECISION DEFAULT 0.0,
    popularity          INTEGER         DEFAULT 0,
    platform_joined_at  TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 5. events  (inclui colunas @Embedded de EventLocation + EventOrganizer)
-- ---------------------------------------------------------------------------
CREATE TABLE events (
    id                      UUID            NOT NULL PRIMARY KEY,
    title                   VARCHAR(200)    NOT NULL,
    subtitle                VARCHAR(500),
    description             VARCHAR(5000),
    image                   VARCHAR(255),
    gallery                 JSONB,
    start_date              TIMESTAMP       NOT NULL,
    end_date                TIMESTAMP       NOT NULL,
    timezone                VARCHAR(50),
    timeline                VARCHAR(20)     NOT NULL,
    status                  VARCHAR(30)     NOT NULL,
    type                    VARCHAR(20)     NOT NULL,

    -- @Embedded EventLocation (6 colunas)
    label                   VARCHAR(255),
    address                 VARCHAR(255),
    city                    VARCHAR(255),
    is_online               BOOLEAN         DEFAULT FALSE,
    map_link                VARCHAR(255),
    directions              VARCHAR(255),

    -- @Embedded EventOrganizer (5 colunas)
    organizer_id            VARCHAR(255),
    organizer_name          VARCHAR(255),
    organizer_avatar        VARCHAR(255),
    organizer_profile_link  VARCHAR(255),
    organizer_contact       VARCHAR(255),

    price_label             VARCHAR(100),
    participants            INTEGER         DEFAULT 0,
    interested              INTEGER         DEFAULT 0,
    is_featured             BOOLEAN         DEFAULT FALSE,
    schedule                JSONB,
    special_guests          JSONB,
    social_links            JSONB,
    related_event_ids       JSONB,
    created_at              TIMESTAMP       NOT NULL,
    updated_at              TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 6. forum_topics  (FK → users)
-- ---------------------------------------------------------------------------
CREATE TABLE forum_topics (
    id                  UUID            NOT NULL PRIMARY KEY,
    author_id           UUID            NOT NULL,
    title               VARCHAR(300)    NOT NULL,
    content             TEXT            NOT NULL,
    category            VARCHAR(30)     NOT NULL,
    tags                JSONB,
    view_count          INTEGER         DEFAULT 0,
    reply_count         INTEGER         DEFAULT 0,
    like_count          INTEGER         DEFAULT 0,
    is_pinned           BOOLEAN         DEFAULT FALSE,
    is_locked           BOOLEAN         DEFAULT FALSE,
    is_solved           BOOLEAN         DEFAULT FALSE,
    created_at          TIMESTAMP       NOT NULL,
    last_activity_at    TIMESTAMP,

    CONSTRAINT fk_forum_topics_author FOREIGN KEY (author_id) REFERENCES users (id)
);

-- ---------------------------------------------------------------------------
-- 7. forum_replies  (FK → forum_topics, users)
-- ---------------------------------------------------------------------------
CREATE TABLE forum_replies (
    id              UUID        NOT NULL PRIMARY KEY,
    topic_id        UUID        NOT NULL,
    author_id       UUID        NOT NULL,
    content         TEXT        NOT NULL,
    likes           INTEGER     DEFAULT 0,
    is_edited       BOOLEAN     DEFAULT FALSE,
    is_best_answer  BOOLEAN     DEFAULT FALSE,
    created_at      TIMESTAMP   NOT NULL,

    CONSTRAINT fk_forum_replies_topic  FOREIGN KEY (topic_id)  REFERENCES forum_topics (id),
    CONSTRAINT fk_forum_replies_author FOREIGN KEY (author_id) REFERENCES users (id)
);

-- ---------------------------------------------------------------------------
-- 8. user_social_links  (FK → users)
-- ---------------------------------------------------------------------------
CREATE TABLE user_social_links (
    id          UUID            NOT NULL PRIMARY KEY,
    user_id     UUID            NOT NULL,
    platform    VARCHAR(50)     NOT NULL,
    url         VARCHAR(500)    NOT NULL,

    CONSTRAINT fk_social_links_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ---------------------------------------------------------------------------
-- 9. user_libraries  (FK → users, UNIQUE user_id+title_id)
-- ---------------------------------------------------------------------------
CREATE TABLE user_libraries (
    id          UUID            NOT NULL PRIMARY KEY,
    user_id     UUID            NOT NULL,
    title_id    VARCHAR(255)    NOT NULL,
    name        VARCHAR(200)    NOT NULL,
    cover       VARCHAR(255),
    type        VARCHAR(50),
    list        VARCHAR(20)     NOT NULL,
    saved_at    TIMESTAMP,

    CONSTRAINT fk_user_libraries_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_user_libraries_user_title UNIQUE (user_id, title_id)
);

-- ---------------------------------------------------------------------------
-- 10. event_tickets  (FK → events)
-- ---------------------------------------------------------------------------
CREATE TABLE event_tickets (
    id          UUID            NOT NULL PRIMARY KEY,
    event_id    UUID            NOT NULL,
    name        VARCHAR(100)    NOT NULL,
    price       VARCHAR(50)     NOT NULL,
    available   INTEGER         DEFAULT 0,

    CONSTRAINT fk_event_tickets_event FOREIGN KEY (event_id) REFERENCES events (id)
);

-- ---------------------------------------------------------------------------
-- 11. event_participants  (FK → events, users, UNIQUE event_id+user_id)
-- ---------------------------------------------------------------------------
CREATE TABLE event_participants (
    id          UUID        NOT NULL PRIMARY KEY,
    event_id    UUID        NOT NULL,
    user_id     UUID        NOT NULL,
    joined_at   TIMESTAMP,

    CONSTRAINT fk_event_participants_event FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_event_participants_user  FOREIGN KEY (user_id)  REFERENCES users (id),
    CONSTRAINT uk_event_participants_event_user UNIQUE (event_id, user_id)
);

-- ---------------------------------------------------------------------------
-- 12. group_members  (FK → groups, users, UNIQUE group_id+user_id)
-- ---------------------------------------------------------------------------
CREATE TABLE group_members (
    id          UUID        NOT NULL PRIMARY KEY,
    group_id    UUID        NOT NULL,
    user_id     UUID        NOT NULL,
    role        VARCHAR(30) NOT NULL,
    joined_at   TIMESTAMP,

    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_group_members_user  FOREIGN KEY (user_id)  REFERENCES users (id),
    CONSTRAINT uk_group_members_group_user UNIQUE (group_id, user_id)
);

-- ---------------------------------------------------------------------------
-- 13. group_works  (FK → groups)
-- ---------------------------------------------------------------------------
CREATE TABLE group_works (
    id          UUID            NOT NULL PRIMARY KEY,
    group_id    UUID            NOT NULL,
    title_id    VARCHAR(255)    NOT NULL,
    title       VARCHAR(200)    NOT NULL,
    cover       VARCHAR(255),
    chapters    INTEGER         DEFAULT 0,
    status      VARCHAR(20)     NOT NULL,
    popularity  INTEGER         DEFAULT 0,
    genres      JSONB           DEFAULT '[]'::jsonb,
    updated_at  TIMESTAMP,

    CONSTRAINT fk_group_works_group FOREIGN KEY (group_id) REFERENCES groups (id)
);

-- ---------------------------------------------------------------------------
-- 14. store_titles  (FK → stores, UNIQUE store_id+title_id)
-- ---------------------------------------------------------------------------
CREATE TABLE store_titles (
    id          UUID            NOT NULL PRIMARY KEY,
    store_id    UUID            NOT NULL,
    title_id    VARCHAR(255)    NOT NULL,
    url         VARCHAR(500),

    CONSTRAINT fk_store_titles_store FOREIGN KEY (store_id) REFERENCES stores (id),
    CONSTRAINT uk_store_titles_store_title UNIQUE (store_id, title_id)
);


-- =============================================================================
-- ÍNDICES em colunas de FK (PostgreSQL não cria automaticamente)
-- =============================================================================
CREATE INDEX idx_forum_topics_author      ON forum_topics (author_id);
CREATE INDEX idx_forum_replies_topic      ON forum_replies (topic_id);
CREATE INDEX idx_forum_replies_author     ON forum_replies (author_id);
CREATE INDEX idx_user_social_links_user   ON user_social_links (user_id);
CREATE INDEX idx_user_libraries_user      ON user_libraries (user_id);
CREATE INDEX idx_event_tickets_event      ON event_tickets (event_id);
CREATE INDEX idx_event_participants_event ON event_participants (event_id);
CREATE INDEX idx_event_participants_user  ON event_participants (user_id);
CREATE INDEX idx_group_members_group      ON group_members (group_id);
CREATE INDEX idx_group_members_user       ON group_members (user_id);
CREATE INDEX idx_group_works_group        ON group_works (group_id);
CREATE INDEX idx_store_titles_store       ON store_titles (store_id);
