-- =============================================================================
-- V2: tags — PK BIGINT com IDENTITY (única tabela sem UUID)
-- =============================================================================

CREATE TABLE tags (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label   VARCHAR(60) NOT NULL UNIQUE
);
