import assert from 'node:assert/strict';
import {copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import test from 'node:test';

const scriptSource = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'brand.mjs');

const brand = {
    name: 'Fixture Brand',
    shortName: 'Fixture',
    slug: 'fixture-brand',
    description: 'Fixture description',
    tagline: 'Fixture tagline',
    publicUrl: 'https://fixture.example',
    apiUrl: 'https://api.fixture.example',
    supportEmail: 'support@fixture.example',
    adminEmail: 'admin@fixture.example',
    emailIdentity: 'Fixture Brand',
};

const generatedPaths = [
    'web/packages/brand/src/index.ts',
    'web/packages/assets/icons/site.webmanifest',
    'web/toonlira/src/shared/config/brand.generated.ts',
    'web/landing-page/src/shared/config/brand.generated.ts',
    'mobile/src/shared/config/brand.generated.ts',
    'api/apps/core/src/main/resources/brand.generated.yml',
    'api/apps/translation-gateway/src/main/resources/brand.generated.yml',
];

const textExtensions = ['.css', '.env', '.html', '.java', '.js', '.json', '.md', '.mjs', '.properties', '.tf', '.toml', '.ts', '.tsx', '.xml', '.yaml', '.yml'];

function defaultRebrand(overrides = {}) {
    return {
        replacements: [{from: 'Legacy Brand', to: 'Fixture Brand'}],
        ignoredDirectories: [],
        ignoredPaths: ['scripts/brand.mjs', 'scripts/config/rebrand.json'],
        semanticAllowlist: [],
        ...overrides,
    };
}

function fixture(t, {brandConfig = brand, rebrandConfig = defaultRebrand()} = {}) {
    const root = resolve(tmpdir(), `brand-script-${crypto.randomUUID()}`);
    const scriptDirectory = resolve(root, 'scripts');

    mkdirSync(resolve(scriptDirectory, 'config'), {recursive: true});
    mkdirSync(resolve(root, 'different-working-directory'));
    copyFileSync(scriptSource, resolve(scriptDirectory, 'brand.mjs'));
    writeFileSync(resolve(scriptDirectory, 'config/brand.json'), typeof brandConfig === 'string' ? brandConfig : JSON.stringify(brandConfig));
    writeFileSync(resolve(scriptDirectory, 'config/rebrand.json'), typeof rebrandConfig === 'string' ? rebrandConfig : JSON.stringify(rebrandConfig));

    t.after(() => rmSync(root, {recursive: true, force: true}));

    return {root, script: resolve(scriptDirectory, 'brand.mjs')};
}

function run(fixtureRoot, script, ...args) {
    return spawnSync(process.execPath, [script, ...args], {
        cwd: resolve(fixtureRoot, 'different-working-directory'),
        encoding: 'utf8',
    });
}

function write(root, relativePath, content) {
    const path = resolve(root, relativePath);

    mkdirSync(dirname(path), {recursive: true});
    writeFileSync(path, content);
}

function expectedGenerated() {
    const javascript = `// Generated by scripts/brand.mjs from scripts/config/brand.json. Do not edit.\nexport const brand = ${JSON.stringify(brand, null, 2)} as const;\n`;

    const yaml = `# Generated by scripts/brand.mjs from scripts/config/brand.json. Do not edit.\napp:\n  brand:\n    name: ${brand.name}\n    short-name: ${brand.shortName}\n    slug: ${brand.slug}\n    description: ${brand.description}\n    tagline: ${brand.tagline}\n    public-url: ${brand.publicUrl}\n    api-url: ${brand.apiUrl}\n    support-email: ${brand.supportEmail}\n    admin-email: ${brand.adminEmail}\n    email-identity: ${brand.emailIdentity}\n`;

    const manifest = `${JSON.stringify({
        name: brand.name,
        short_name: brand.shortName,
        icons: [
            {src: '/android-chrome-192x192.png', sizes: '192x192', type: 'image/png'},
            {src: '/android-chrome-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable'},
        ],
        theme_color: '#161616',
        background_color: '#161616',
        display: 'standalone',
        start_url: '/',
    }, null, 2)}\n`;

    return new Map([
        ['web/packages/brand/src/index.ts', javascript],
        ['web/packages/assets/icons/site.webmanifest', manifest],
        ['web/toonlira/src/shared/config/brand.generated.ts', javascript],
        ['web/landing-page/src/shared/config/brand.generated.ts', javascript],
        ['mobile/src/shared/config/brand.generated.ts', javascript],
        ['api/apps/core/src/main/resources/brand.generated.yml', yaml],
        ['api/apps/translation-gateway/src/main/resources/brand.generated.yml', yaml],
    ]);
}

test('rejeita operações, modos e argumentos inválidos', t => {
    const {root, script} = fixture(t);

    for (const args of [[], ['generate', '--apply'], ['rebrand'], ['rebrand', '--other'], ['generate', '--check', 'extra']]) {
        const result = run(root, script, ...args);

        assert.notEqual(result.status, 0, args.join(' '));
        assert.match(result.stderr, /Usage: brand\.mjs generate/);
    }
});

test('gera os sete artefatos com conteúdo exato a partir de outro cwd', t => {
    const {root, script} = fixture(t);

    const result = run(root, script, 'generate');

    assert.equal(result.status, 0, result.stderr);

    for (const [relativePath, expected] of expectedGenerated())
      assert.equal(readFileSync(resolve(root, relativePath), 'utf8'), expected, relativePath);
});

test('detecta artefatos ausentes e obsoletos sem escrevê-los em generate --check', t => {
    const {root, script} = fixture(t);

    const missingPath = generatedPaths.at(-1);

    for (const relativePath of generatedPaths.filter(path => path !== missingPath))
      write(root, relativePath, 'outdated artifact');

    const result = run(root, script, 'generate', '--check');

    assert.equal(result.status, 1);

    for (const relativePath of generatedPaths) {
        assert.match(result.stderr, new RegExp(`Outdated brand artifact: ${relativePath.replace(/[./]/g, '\\$&')}`));

        if (relativePath === missingPath)
          assert.equal(existsSync(resolve(root, relativePath)), false);
        else
          assert.equal(readFileSync(resolve(root, relativePath), 'utf8'), 'outdated artifact');
    }
});

test('aceita generate --check limpo e mantém a geração idempotente', t => {
    const {root, script} = fixture(t);

    assert.equal(run(root, script, 'generate').status, 0);

    const before = new Map(generatedPaths.map(path => [path, readFileSync(resolve(root, path), 'utf8')]));

    const check = run(root, script, 'generate', '--check');
    const secondGeneration = run(root, script, 'generate');

    assert.equal(check.status, 0, check.stderr);
    assert.equal(check.stderr, '');
    assert.equal(secondGeneration.status, 0, secondGeneration.stderr);

    for (const [relativePath, content] of before)
      assert.equal(readFileSync(resolve(root, relativePath), 'utf8'), content);
});

test('propaga configurações de geração inválidas sem produzir artefatos', t => {
    const {root, script} = fixture(t, {brandConfig: '{invalid json'});

    const result = run(root, script, 'generate');

    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /SyntaxError/);
    assert.equal(existsSync(resolve(root, generatedPaths[0])), false);
});

test('aprova auditoria de rebrand sem ocorrências acionáveis', t => {
    const {root, script} = fixture(t);

    write(root, 'nested/clean.md', 'Current brand only');

    const result = run(root, script, 'rebrand', '--check');

    assert.equal(result.status, 0, result.stdout);
    assert.match(result.stdout, /Rebrand audit: 0 actionable pattern\(s\), 0 allowed pattern\(s\), no files changed\./);
});

test('reporta ocorrências acionáveis no check sem modificar arquivos', t => {
    const {root, script} = fixture(t);

    const content = 'Legacy Brand and Legacy Brand';

    write(root, 'nested/copy.md', content);

    const result = run(root, script, 'rebrand', '--check');

    assert.equal(result.status, 1);
    assert.match(result.stdout, /ACTIONABLE nested\/copy\.md: Legacy Brand \(2\)/);
    assert.match(result.stdout, /Rebrand audit: 1 actionable pattern\(s\), 0 allowed pattern\(s\), no files changed\./);
    assert.equal(readFileSync(resolve(root, 'nested/copy.md'), 'utf8'), content);
});

test('preserva ocorrências permitidas em check e apply', t => {
    const rebrandConfig = defaultRebrand({
        semanticAllowlist: [{path: 'docs/meaning.md', text: 'Legacy Brand', reason: 'Functional term.'}],
    });

    const {root, script} = fixture(t, {rebrandConfig});

    const content = 'Legacy Brand';

    write(root, 'docs/meaning.md', content);

    const check = run(root, script, 'rebrand', '--check');
    const apply = run(root, script, 'rebrand', '--apply');

    assert.equal(check.status, 0, check.stdout);
    assert.match(check.stdout, /ALLOWED docs\/meaning\.md: Legacy Brand \(1\) — Functional term\./);
    assert.match(check.stdout, /0 actionable pattern\(s\), 1 allowed pattern\(s\)/);
    assert.equal(apply.status, 0, apply.stdout);
    assert.match(apply.stdout, /0 file\(s\) updated\./);
    assert.equal(readFileSync(resolve(root, 'docs/meaning.md'), 'utf8'), content);
});

test('aplica todas as ocorrências acionáveis e informa arquivos atualizados', t => {
    const {root, script} = fixture(t);

    write(root, 'one.md', 'Legacy Brand Legacy Brand');
    write(root, 'nested/two.ts', 'Legacy Brand');

    const result = run(root, script, 'rebrand', '--apply');

    assert.equal(result.status, 0, result.stderr);
    assert.match(result.stdout, /ACTIONABLE one\.md: Legacy Brand \(2\)/);
    assert.match(result.stdout, /ACTIONABLE nested\/two\.ts: Legacy Brand \(1\)/);
    assert.match(result.stdout, /Rebrand audit: 2 actionable pattern\(s\), 0 allowed pattern\(s\), 2 file\(s\) updated\./);
    assert.equal(readFileSync(resolve(root, 'one.md'), 'utf8'), 'Fixture Brand Fixture Brand');
    assert.equal(readFileSync(resolve(root, 'nested/two.ts'), 'utf8'), 'Fixture Brand');
});

test('varre extensões textuais recursivamente e ignora caminhos configurados, binários e arquivos grandes', t => {
    const rebrandConfig = defaultRebrand({
        ignoredDirectories: ['ignored-directory'],
        ignoredPaths: ['scripts/brand.mjs', 'scripts/config/rebrand.json', 'ignored-path.md'],
    });

    const {root, script} = fixture(t, {rebrandConfig});

    for (const extension of textExtensions)
      write(root, `nested/file${extension}`, 'Legacy Brand');

    write(root, 'ignored-directory/inside.md', 'Legacy Brand');
    write(root, 'ignored-path.md', 'Legacy Brand');
    write(root, 'binary.bin', 'Legacy Brand');
    write(root, 'large.md', `${'x'.repeat(2_000_000)}Legacy Brand`);

    const result = run(root, script, 'rebrand', '--apply');

    assert.equal(result.status, 0, result.stderr);
    assert.match(result.stdout, /Rebrand audit: 16 actionable pattern\(s\), 0 allowed pattern\(s\), 16 file\(s\) updated\./);

    for (const extension of textExtensions)
      assert.equal(readFileSync(resolve(root, `nested/file${extension}`), 'utf8'), 'Fixture Brand');

    for (const relativePath of ['ignored-directory/inside.md', 'ignored-path.md', 'binary.bin', 'large.md'])
      assert.match(readFileSync(resolve(root, relativePath), 'utf8'), /Legacy Brand/);
});

test('propaga configurações de rebrand inválidas sem alterar arquivos', t => {
    const {root, script} = fixture(t, {rebrandConfig: '{invalid json'});

    const content = 'Legacy Brand';

    write(root, 'copy.md', content);

    const result = run(root, script, 'rebrand', '--apply');

    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /SyntaxError/);
    assert.equal(readFileSync(resolve(root, 'copy.md'), 'utf8'), content);
});
