import {
    Bell,
    Bookmark,
    Calendar,
    Check,
    ChevronLeft,
    ChevronRight,
    Clock,
    Eye,
    Heart,
    Home,
    Library,
    Menu,
    MessageSquare,
    MessagesSquare,
    Newspaper,
    Plus,
    Search,
    Sparkles,
    TrendingUp,
    User,
    X,
    type LucideIcon,
} from 'lucide-react';

/** Mapa nome (referência do handoff) → ícone lucide-react. */
export const forumIcon: Record<string, LucideIcon> = {
    home: Home,
    forum: MessagesSquare,
    library: Library,
    news: Newspaper,
    eye: Eye,
    sparkle: Sparkles,
    heart: Heart,
    calendar: Calendar,
    comment: MessageSquare,
    bell: Bell,
    trending: TrendingUp,
    clock: Clock,
    bookmark: Bookmark,
    user: User,
    plus: Plus,
    search: Search,
    menu: Menu,
    close: X,
    chevronL: ChevronLeft,
    chevronR: ChevronRight,
    check: Check,
};
