package com.mangareader.domain.analytics.entity;

public enum BehaviorEventType {
    LIBRARY_ITEM_ADDED,
    LIBRARY_ITEM_REMOVED,
    LIBRARY_LIST_CHANGED,
    PROFILE_RECOMMENDATION_ADDED,
    PROFILE_RECOMMENDATION_REMOVED,
    PROFILE_RECOMMENDATION_REORDERED,
    SUBSCRIPTION_CREATED,
    CHAPTER_COMPLETED,
    TITLE_VIEW_QUALIFIED,
    TITLE_VIEW_BOUNCE,
    CHAPTER_SESSION_STARTED,
    CHAPTER_PROGRESS_CHECKPOINT,
    CHAPTER_SESSION_COMPLETED,
    CHAPTER_SESSION_PARTIAL,
    CHAPTER_NEXT_OPENED,
    CHAPTER_RETURNED,
    CHAPTER_REREAD,
    SEARCH_PERFORMED,
    SEARCH_NO_RESULTS,
    SEARCH_RESULT_CLICKED,
    CATALOG_FILTER_APPLIED,
    STORE_OUTBOUND_CLICK;

    public boolean acceptsClientSubmission() {
        return switch (this) {
            case TITLE_VIEW_QUALIFIED, TITLE_VIEW_BOUNCE, CHAPTER_SESSION_STARTED,
                    CHAPTER_PROGRESS_CHECKPOINT, CHAPTER_SESSION_COMPLETED, CHAPTER_SESSION_PARTIAL,
                    CHAPTER_NEXT_OPENED, CHAPTER_RETURNED, CHAPTER_REREAD, SEARCH_PERFORMED,
                    SEARCH_NO_RESULTS, SEARCH_RESULT_CLICKED, CATALOG_FILTER_APPLIED,
                    STORE_OUTBOUND_CLICK -> true;
            default -> false;
        };
    }
}
