/**
 * Brand maintenance is contextual: review every rebrand mapping and audit
 * finding before adding a replacement. Terms such as "manga reader" can
 * describe the manga-reading feature rather than the public brand, so valid
 * domain text belongs in the semantic allowlist instead of auto-replacement.
 *
 * Usage:
 *   node scripts/brand.mjs generate [--check]
 *   node scripts/brand.mjs rebrand --check
 *   node scripts/brand.mjs rebrand --apply
 */
import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const [operation, mode] = process.argv.slice(2);

const validMode = (operation === 'generate' && (!mode || mode === '--check'))
  || (operation === 'rebrand' && ['--check', '--apply'].includes(mode));

if (!validMode || process.argv.length > 4) {
  throw new Error('Usage: brand.mjs generate [--check] | rebrand --check | rebrand --apply');
}

async function generate(checkOnly) {
  const brand = JSON.parse(await readFile(resolve(root, 'scripts/config/brand.json'), 'utf8'));
  const javascript = `// Generated by scripts/brand.mjs from scripts/config/brand.json. Do not edit.\nexport const brand = ${JSON.stringify(brand, null, 2)} as const;\n`;
  const yaml = `# Generated by scripts/brand.mjs from scripts/config/brand.json. Do not edit.\napp:\n  brand:\n    name: ${brand.name}\n    short-name: ${brand.shortName}\n    slug: ${brand.slug}\n    description: ${brand.description}\n    tagline: ${brand.tagline}\n    public-url: ${brand.publicUrl}\n    api-url: ${brand.apiUrl}\n    support-email: ${brand.supportEmail}\n    admin-email: ${brand.adminEmail}\n    email-identity: ${brand.emailIdentity}\n`;
  const webManifest = `${JSON.stringify({ name: brand.name, short_name: brand.shortName, icons: [{ src: '/android-chrome-192x192.png', sizes: '192x192', type: 'image/png' }, { src: '/android-chrome-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable' }], theme_color: '#161616', background_color: '#161616', display: 'standalone', start_url: '/' }, null, 2)}\n`;
  const outputs = new Map([
    ['web/packages/brand/src/index.ts', javascript], ['web/packages/assets/icons/site.webmanifest', webManifest],
    ['web/toonlira/src/shared/config/brand.generated.ts', javascript], ['web/landing-page/src/shared/config/brand.generated.ts', javascript],
    ['mobile/src/shared/config/brand.generated.ts', javascript], ['api/apps/core/src/main/resources/brand.generated.yml', yaml],
    ['api/apps/translation-gateway/src/main/resources/brand.generated.yml', yaml],
  ]);
  let stale = false;
  for (const [relativePath, content] of outputs) {
    const path = resolve(root, relativePath);
    let existing;
    try { existing = await readFile(path, 'utf8'); } catch (error) { if (error.code !== 'ENOENT') throw error; }
    if (existing === content) continue;
    stale = true;
    if (checkOnly) console.error(`Outdated brand artifact: ${relativePath}`);
    else { await mkdir(dirname(path), { recursive: true }); await writeFile(path, content); }
  }
  if (checkOnly && stale) process.exitCode = 1;
}

async function textFiles(directory, ignoredDirectories, ignoredPaths) {
  const entries = await readdir(directory, { withFileTypes: true });
  const extensions = new Set(['.css', '.env', '.html', '.java', '.js', '.json', '.md', '.mjs', '.properties', '.tf', '.toml', '.ts', '.tsx', '.xml', '.yaml', '.yml']);
  const files = [];
  for (const entry of entries) {
    if (entry.isDirectory()) { if (!ignoredDirectories.has(entry.name)) files.push(...await textFiles(resolve(directory, entry.name), ignoredDirectories, ignoredPaths)); continue; }
    const path = resolve(directory, entry.name);
    const extension = entry.name.slice(entry.name.lastIndexOf('.'));
    if (entry.isFile() && !ignoredPaths.has(relative(root, path)) && extensions.has(extension)) files.push(path);
  }
  return files;
}

async function rebrand(apply) {
  const config = JSON.parse(await readFile(resolve(root, 'scripts/config/rebrand.json'), 'utf8'));
  const allowlist = new Map(config.semanticAllowlist.map(item => [`${item.path}\u0000${item.text}`, item.reason]));
  const files = await textFiles(root, new Set(config.ignoredDirectories), new Set(config.ignoredPaths));
  const findings = [];
  let changedFiles = 0;
  for (const path of files) {
    const relativePath = relative(root, path);
    if ((await stat(path)).size > 2_000_000) continue;
    const original = await readFile(path, 'utf8');
    let updated = original;
    for (const replacement of config.replacements) {
      const count = updated.split(replacement.from).length - 1;
      if (!count) continue;
      const reason = allowlist.get(`${relativePath}\u0000${replacement.from}`);
      if (reason) { findings.push({ relativePath, from: replacement.from, count, status: 'allowed', reason }); continue; }
      findings.push({ relativePath, from: replacement.from, count, status: 'actionable' });
      updated = updated.split(replacement.from).join(replacement.to);
    }
    if (apply && updated !== original) { await writeFile(path, updated); changedFiles += 1; }
  }
  for (const finding of findings) console.log(`${finding.status.toUpperCase()} ${finding.relativePath}: ${finding.from} (${finding.count})${finding.reason ? ` — ${finding.reason}` : ''}`);
  const actionable = findings.filter(finding => finding.status === 'actionable');
  console.log(`Rebrand audit: ${actionable.length} actionable pattern(s), ${findings.length - actionable.length} allowed pattern(s), ${apply ? `${changedFiles} file(s) updated` : 'no files changed'}.`);
  if (!apply && actionable.length) process.exitCode = 1;
}

if (operation === 'generate') await generate(mode === '--check');
else await rebrand(mode === '--apply');
